apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - env:
        image: linuxserver/unifi-controller:amd64-latest
        imagePullPolicy: Always
        name: unifi-controller
        ports:
        - containerPort: 8443
        volumeMounts:
          - mountPath: /unifi
            name: unifi-config
      volumes:
      - name: unifi-config
        hostPath:
          path: /unifi