apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-lb-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-lb-shared-ip
spec:
  ports:
  - name: stun-service
    protocol: UDP
    port: 3478
    targetPort: 3478
  - name: remote-syslog
    protocol: UDP
    port: 5514
    targetPort: 5514
  - name: device-discovery
    protocol: UDP
    port: 10001
    targetPort: 10001
  - name: controller-discoverable-l2
    protocol: UDP
    port: 1900
    targetPort: 1900
  selector:
    app: unifi-controller
  type: LoadBalancer