apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-lb-shared-ip
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: unifi-controller
  type: LoadBalancer