apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-lb-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-lb-shared-ip
spec:
  ports:
  - port: 8443
    targetPort: 8443
    - port: 8080
    targetPort: 8080
    - port: 8843
    targetPort: 8843
    - port: 8880
    targetPort: 8880
    - port: 6789
    targetPort: 6789
    - port: 5514
    targetPort: 5514
  selector:
    app: unifi-controller
  type: LoadBalancer