apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - env:
        image: linuxserver/unifi-controller:amd64-latest
        imagePullPolicy: Always
        name: unifi-controller
        ports:
        - containerPort: 8443
        - containerPort: 8080
        - containerPort: 8843
        - containerPort: 8880
        - containerPort: 6789
        volumeMounts:
          - mountPath: /unifi/data
            name: unifi-data
            subPath: data
          - mountPath: /unifi/log
            name: unifi-data
            subPath: log
          - mountPath: /unifi/cert
            name: unifi-data
            subPath: cert
          - mountPath: /unifi/init.d
            name: unifi-data
            subPath: init.d
      volumes:
      - name: unifi-data
        persistentVolumeClaim:
          claimName: unifi