apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - env:
        image: linuxserver/unifi-controller:amd64-latest
        imagePullPolicy: Always
        name: unifi-controller
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8843
          protocol: TCP
        - containerPort: 8880
          protocol: TCP
        - containerPort: 6789
          protocol: TCP
        - containerPort: 3478
          protocol: UDP
        - containerPort: 5514
          protocol: UDP
        - containerPort: 10001
          protocol: UDP
        - containerPort: 1900
          protocol: UDP
        volumeMounts:
          - mountPath: /config
            name: unifi-data
      volumes:
      - name: unifi-data
        persistentVolumeClaim:
          claimName: unifi