apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-lb-tcp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-lb-shared-ip
spec:
  ports:
  - name: gui-https
    port: 8443
    targetPort: 8443
  - name: controller
    port: 8080
    targetPort: 8080
  - name: captive-https
    port: 8843
    targetPort: 8843
  - name: captive-http
    port: 8880
    targetPort: 8880
  - name: speed-test
    port: 6789
    targetPort: 6789
  selector:
    app: unifi-controller
  type: LoadBalancer